### ISSUE TITLE
expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by viboji** [edelvarden/ComfyUI-ImageMetadataExtension#2]
Its not saving showing some error "expected str, bytes or os.PathLike object, not NoneType"
![image](https://github.com/user-attachments/assets/0d0a709f-e16d-471c-80b0-3500c6d49c03)

this node works when i switch  "include_extra_metadata" to false but then its the same as regular save image node.

**Comment by edelvarden** [comment]
What node settings do you use besides `include_extra_metadata`?
